---
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 9
  jsx: true
env:
  commonjs: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
